### PR TITLE
Add support for logic element "nvBit".

### PR DESCRIPTION
**Pull request by SvenRosvall**
Needed for visibilityLogic used by descriptor file for CANCMD.

### CODE REVIEW

**Comment by david284** [comment]
I'd consider adding a check that argument3 exists - reason is, javascript allows calling without all the arguments, and I've used that 'feature' in logic element 'nv' which doesn't use argument3, so the call for 'nv' doesn't need argument3, so not present
So if someone copies the call for 'nv' when adding 'nvBits', it'll fail

**Comment by SvenRosvall** [comment]
I didn't use argument3 partly as I didn't know what it is for, the name doesn't give me a hint. Looking at the code for "evBits" it looks like argument3 is some index into the event table. Looking at calls to parseLogicElement() seems to confirm this. So for anything related to NVs the argument3 is not set. So I don't see a purpose for argument3 in the code for "nvBits". 

If there would be any check for argument3 it would be to ensure that argument3 is NOT set because if argument3 is set we are in the context of event variables and the "nv" and "nvBits" expressions wouldn't be valid there.

**Comment by david284** [comment]
Yep, I should have commented that the meaning of argument3 is dependant on the logic case
(I did put that inside evBits, but it ought to be at the top level)
But my mistake, I thought you where using argument 3 (as the comment is still in your code) but on closer inspection I see you're not using it anyway, so it's not a problem

**Comment by SvenRosvall** [comment]
Oops, Sorry, forgot about that comment.

**Pull request merged**
